ACTIONS_CHECKOUT_VERSION := 4
ACTIONS_CREATE_RELEASE_VERSION := 1
ACTIONS_SETUP_GO_VERSION := 5
CERT_MANAGER_VERSION := 1.18.2
CONTOUR_VERSION := 1.32.0
ENVTEST_K8S_VERSION := 1.33.0
EXTERNAL_DNS_VERSION := 0.18.0
GH_VERSION := 2.68.1
YQ_VERSION := 4.45.1

# Follow the kustomize version installed in the Argo CD container
# https://github.com/cybozu/neco-containers/blob/main/argocd/Dockerfile#L10
KUSTOMIZE_VERSION := 5.4.3
