ACTIONS_CHECKOUT_VERSION := 4
ACTIONS_CREATE_RELEASE_VERSION := 1
ACTIONS_SETUP_GO_VERSION := 5
CERT_MANAGER_VERSION := 1.16.1
CONTOUR_VERSION := 1.30.1
ENVTEST_K8S_VERSION := 1.31.0
EXTERNAL_DNS_VERSION := 0.15.0
GH_VERSION := 2.62.0
YQ_VERSION := 4.44.5

# Follow the kustomize version installed in the Argo CD container
# https://github.com/cybozu/neco-containers/blob/main/argocd/Dockerfile#L10
KUSTOMIZE_VERSION := 5.2.1
