name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  image:
    name: Push container image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'
      - uses: ./.github/actions/aqua
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: make setup
      - run: make check-generate
      - run: make lint
      - run: make test
      - run: make docker-build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push versioned image to ghcr.io
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          docker tag ghcr.io/cybozu-go/contour-plus:latest ghcr.io/cybozu-go/contour-plus:$TAG
          docker push ghcr.io/cybozu-go/contour-plus:$TAG
      - name: Push latest image to ghcr.io
        if: ${{ !contains(github.ref, '-') }}
        run: docker push ghcr.io/cybozu-go/contour-plus:latest
  release:
    name: Release on GitHub
    needs: image
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          gh release create "${TAG}" \
            --title "Release ${TAG}" \
            --notes "See [CHANGELOG.md](./CHANGELOG.md) for details." \
            $([[ "${TAG}" == *-* ]] && echo --prerelease)
